services:
  postgres:
    image: postgres:latest
    container_name: pg-koservice
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: Admin123!
      POSTGRES_DB: koservice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d koservice"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-koservice
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: Admin123!
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: